### ISSUE TITLE
Crosswalk Detector

### ISSUE THREAD

**Issue by fabolhak** [tum-phoenix/drive_ros_image_recognition#10]
A crosswalk should be detected in order to stop in front of pedestrians. The detector should be robust against noise (other street markings) and computationally cheap. 

More infos in [carolocups rules](https://wiki.ifr.ing.tu-bs.de/carolocup/en/system/files/Carolo-Cup%20Regulations.pdf) (section "5.3.6.4 Crosswalks").

# tasks
- [ ] download rosbags with crosswalks from [Phoenix bag database](http://cloud.tum-phoenix.de/) (e.g. [this one](http://cloud.tum-phoenix.de/bags/download?bagId=29) or [this one](http://cloud.tum-phoenix.de/bags/download?bagId=22)) 
- [ ] develop detector
- [ ] Check the porting from LMS (https://github.com/tum-phoenix/drive_ros_image_recognition/issues/3)
- [ ] validate detector on a bag with different scenarios

# resources
- [ROS Image transport tutorial](http://wiki.ros.org/image_transport/Tutorials)
- [carolocup 2018 rules](https://wiki.ifr.ing.tu-bs.de/carolocup/en/system/files/Basic%20Cup%20Regulations.pdf)
- [Nvidia OpenCV Tutorials](https://developer.nvidia.com/embedded/learn/tutorials#collapseOpenCV)

# image
![32417202-25614ece-c256-11e7-8a72-7a0fc80053e1](https://user-images.githubusercontent.com/20029691/32995652-e9017134-cd77-11e7-9f8c-539c4ea78234.png)
