### ISSUE TITLE
Barred Area Detector

### ISSUE THREAD

**Issue by fabolhak** [tum-phoenix/drive_ros_image_recognition#11]
Barred areas should be detected in order avoid them. The detector should be robust against noise (other street markings) and computationally cheap. 

More infos in [carolocups rules](https://wiki.ifr.ing.tu-bs.de/carolocup/en/system/files/Carolo-Cup%20Regulations.pdf) (section "5.3.6.3 Barred Area").

# tasks CC19
- [x] design and print pattern (so that we can easily apply and remove it from the track)
- [x] record some data with the pattern
- [x] develop detector
- [x] validate detector on a bag with different scenarios

# task CC20
- [ ] Evaluate approach from CC19, which is with SVM.
- [ ] Try to add barred areas and street markings into object detection (https://github.com/tum-phoenix/drive_project_management/issues/15)
- [ ] Try a different approach if nessary. 
- [ ] Check if the car can pass barred areas, safely

# resources
- [ROS Image transport tutorial](http://wiki.ros.org/image_transport/Tutorials)
- [carolocup 2018 rules](https://wiki.ifr.ing.tu-bs.de/carolocup/en/system/files/Basic%20Cup%20Regulations.pdf)
- [Nvidia OpenCV Tutorials](https://developer.nvidia.com/embedded/learn/tutorials#collapseOpenCV)

# image
![32417202-25614ece-c256-11e7-8a72-7a0fc80053e1](https://user-images.githubusercontent.com/20029691/32995692-a603fa5e-cd78-11e7-8717-0cef535e051f.png)

**Comment by MaslinuPoimal** [comment]
SVM-based approaches for this found to be working well. Move to https://github.com/tum-phoenix/drive_ros_street_marker_detection
