### ISSUE TITLE
[LDCA/LDML] Lane Detection

### ISSUE THREAD

**Issue by a-0-dev** [tum-phoenix/drive_ros_image_recognition#13]
# Objective: Lane Detection for our CC20 Car
The lane Detection is an important task in autonomous driving.

# Goal
- Stable and fast line detection for trajectory generation
- detect the current lane and identify the different lines and line types (outer left, middle, double, solid, dashed)
- Robustness against missing line parts (Broken lines are part of the cup)
- Robustness against obstacles and ramp
- handling for curves
- handling of crossings and intersections with priority lines.
- Pedestrian island and zebra crossings

## Setup:
Our previous line detection can be found:
https://github.com/tum-phoenix/drive_ros_image_recognition/tree/polynom
You can try different computer vision approaches or machine learning approaches.
- Machine learning - line detection
For the machine learning approach there is also a different issue:
https://github.com/tum-phoenix/drive_ml/issues/19
- Hough lines
- Road segmentation
- ...

A template with basic functions can be found under:
https://github.com/tum-phoenix/drive_ml/issues/19

## Tasks:
- [ ] Implement one or more line detection approaches (for comparison)
- [ ] Focus on line detection and trajectory at first and check the stability of the trajectory
- [ ] Extract polynomial for the trajectory and the environment model
- [ ] Detect the current lane and identify the different lines and line types
- [ ] Detect Crossings and special street parts, like islands
- [ ] Estimate the curvation radius
- [ ] Compare different approaches

**Comment by xXBasti** [comment]
Maybe that can be helpful:
https://github.com/tatsuyah/Lane-Lines-Detection-Python-OpenCV
