### ISSUE TITLE
Startline Detector

### ISSUE THREAD

**Issue by fabolhak** [tum-phoenix/drive_ros_image_recognition#8]
A startline should be detected, because we need to know where the "parking zone" starts:
> The starting line (a checkered line of approx. 50 mm) marks the beginning of the track, which is the parking zone (cf. Section A.1.1).

The detector should be robust against noise (other street markings) and computationally cheap.

# tasks CC19
- [x] download rosbags with startlines from [Phoenix bag database](http://cloud.tum-phoenix.de/) (e.g. [this one](http://cloud.tum-phoenix.de/bags/download?bagId=21)) 
- [x] develop detector
- [x] validate detector on a bag with different scenarios

# tasks CC20
- [ ] Evaluate the current SVM Approach

# resources
- [ROS Image transport tutorial](http://wiki.ros.org/image_transport/Tutorials)
- [carolocup 2018 rules](https://wiki.ifr.ing.tu-bs.de/carolocup/en/system/files/Basic%20Cup%20Regulations.pdf)
- [Nvidia OpenCV Tutorials](https://developer.nvidia.com/embedded/learn/tutorials#collapseOpenCV)

# images
![screenshot_2017-11-09_16-02-57](https://user-images.githubusercontent.com/20029691/32612072-932f7fac-c567-11e7-8144-584f25deda80.png)
